spring:
  datasource:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb;MODE=Oracle
    username: sa
    password:
  resources:
    chain:
      cache: false
  jpa:
    hibernate:
    ddl-auto: validate   
   
  liquibase:
    change-log: classpath:db/liquibase/db.changelog-test.xml
    user: sa
    password: 
        
opentracing:
  jaeger:
    enabled: false
    
# ----------------------------------------
# APPLICATION PARAMETERS
# ----------------------------------------
corsAllowedOrigin : "*"

tomcatGracefulShutdownTimeout: 30

logging.config: classpath:logback.xml